# Generated by Django 4.2.5 on 2023-10-20 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(max_length=3)),
                ('Croom', models.CharField(max_length=3)),
                ('area', models.CharField(max_length=10)),
                ('balcony', models.BooleanField(default=False)),
                ('numofkv', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=100)),
                ('numofhome', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('prommisse', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='immovable.role')),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoEmp', models.ImageField(upload_to='photos/')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=10)),
                ('hire', models.DateField(auto_now_add=True)),
                ('depart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='immovable.department')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='immovable.employee')),
            ],
        ),
        migrations.CreateModel(
            name='contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfSign', models.DateField()),
                ('Buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='immovable.users')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='immovable.employee')),
                ('home', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='immovable.home')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='immovable.status')),
            ],
        ),
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20)),
                ('Home', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='immovable.home')),
                ('Users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='immovable.users')),
            ],
        ),
    ]
