# Generated by Django 4.2.5 on 2023-10-20 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immovable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='Users',
        ),
    ]
