# Generated by Django 4.2.5 on 2023-10-23 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('immovable', '0002_remove_application_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='home',
        ),
        migrations.AddField(
            model_name='contract',
            name='appl',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='immovable.application'),
        ),
    ]
