# Generated by Django 4.2.5 on 2023-10-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immovable', '0003_remove_contract_home_contract_appl'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='Resprice',
            field=models.IntegerField(default=3000),
        ),
    ]
